config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/signup',   to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update-basic-info',  to: 'users#update_basic_info'
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  resources :users do
    resources :attendances, only: :create
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :attendances, dependent: :destroy

  
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :department, length: { in: 3..50 }, allow_blank: true

  
  def self.search(search) #ここでのself.はUser.を意味する
    if search
      where(['name LIKE ?', "%#{search}%"]) #検索とnameの部分一致を表示。User.は省略
    else
      all #全て表示。User.は省略
    end
  end
  
  class << self

  # 渡された文字列のハッシュ値を返す

    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :  # Userクラスにnew_tokenを渡したクラスメソッドを作成
                                                    BCrypt::Engine.cost         # SecureRandomモジュールにbase64でランダムな文字列を生成
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token                                                               # 記憶トークンをremember_token属性に代入 
      SecureRandom.urlsafe_base64                                               # DBのremember_token属性値をBcryptに渡してハッシュ化して更新
    end
  end

  # 記憶トークンをUserオブジェクトのremember_token属性に代入し、DBに記憶ダイジェストとして保存
  def remember
    self.remember_token = User.new_token                                        # 記憶トークンをremember_token属性に代入 
    update_attribute(:remember_digest, User.digest(remember_token))             # DBのremember_token属性値をBcryptに渡してハッシュ化して更新
  end

    # 引数として受け取った値を記憶トークンに代入して暗号化（記憶ダイジェスト）し、DBにいるユーザーの記憶ダイジェストと比較、同一ならtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?                                        # 記憶ダイジェストがnilの場合、falseを戻り値として返す
    BCrypt::Password.new(remember_digest).is_password?(remember_token)          # DBの記憶ダイジェストと、受け取った記憶トークンを記憶ダイジェストにした値を比較
  end
  
  def forget
    update_attribute(:remember_digest, nil)                                     # DBにある記憶ダイジェストをnilにする
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy, :edit_basic_info, :update_basic_info]
  before_action :ensure_correct_user,   only: [:edit, :update, :show]

  def index
   @users = User.paginate(page: params[:page]).search(params[:search])
  end

   def show
    @user = User.find(params[:id])
    @first_day = first_day(params[:first_day])
    @last_day = @first_day.end_of_month
    (@first_day..@last_day).each do |day|
      unless @user.attendances.any? {|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    @dates = user_attendances_month_date
    @worked_sum = @dates.where.not(started_at: nil).count
   end
  

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザーの新規作成に成功しました。"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
    @user = User.find(params[:id])
  end
  
  def update_basic_info
  @user = User.find(params[:id])
  if @user.update_attributes(basic_info_params)
    flash[:success] = "基本情報を更新しました。"
    redirect_to @user   
  else
    render 'edit_basic_info'
  end
  end
  
  


  private

    def user_params
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end
    
    def basic_info_params
    params.require(:user).permit(:basic_time, :work_time)
    end

    # beforeアクション

    # ログイン済みユーザーか確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
    def ensure_correct_user
      if current_user.id != params[:id].to_i && !current_user.admin?
        flash[:danger] = "権限がありません"
        redirect_to root_path
      end
    end
    

end

app/helpers/users_helper.rb
module UsersHelper
    
        # 基本時間などの値を、指定の書式にフォーマットして返す
    def format_basic_time(datetime)
      format("%.2f", ((datetime.hour * 60) + datetime.min)/60.0)
    end
    

    
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
  
  <%= f.label :department %>
  <%= f.text_field :department, class: 'form-control' %>
  

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_overwork-modal.html.erb
<div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="Modal" aria-hidden="true">
  <!--以下modal-dialogのCSSの部分で modal-lgやmodal-smを追加するとモーダルのサイズを変更することができる-->
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
          <span class="modal-close" aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="Modal">[残業申請]</h5>
      </div>
      <div class="modal-body">
        <table class = "table-bordered table-striped table-condensed">
         <thead>
            <tr> <!--rowspan:縦結合、colspan：横結合-->
              <th colspan="1">日付</th>
              <th colspan="1">曜日</th>
              <th colspan="3">終了予定時間</th>
              <th colspan="1">翌日</th>
              <th colspan="3">業務処理内容</th>
              <th colspan="3">支持者確認印</th>
            </tr>
        </thead>
        <tbody>
            <tr class="overwork-input">
              <td id="recipient-date"></td>
              <td id="recipient-youbi"></td>
              <td colspan="3"><input type="time"></td>
              <td ><label>
                    <input type="checkbox" name="overwork-checkbox">
                   </label>
              </td>
              <td colspan="3"><input type="text"></td>
              <td colspan="3"><label>
                                <select name="frequency_id">
                                  <option value="1">上長１</option>
                                  <option value="2">上長２</option>
                                </select>
                              </label>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">変更を送信する</button>
      </div>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<script>$('#Modal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) //モーダルを呼び出すときに使われたボタンを取得
  var date = button.data('date') //data- の値を取得
  var youbi = button.data('youbi')
  var modal = $(this)  //モーダルを取得
  modal.find('.modal-body td#recipient-date').text(date)
  modal.find('.modal-body td#recipient-youbi').text(youbi)
})</script>


            
            

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    ｜<%= link_to "基本情報編集", basic_info_path(user) %>
    ｜<%= link_to "削除", user, method: :delete, data: { confirm: "削除してよろしいですか？" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'アカウント編集') %>
<% provide(:button_text, '更新する') %>
<h1>アカウント情報の更新</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報編集") %>

<h1>基本情報の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: update_basic_info_path(params: {id: @user.id})) do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <%= f.label "基本時間" %>
      <%= f.time_field :basic_time, class: 'form-control' %>

      <%= f.label "指定勤務時間" %>
      <%= f.time_field :work_time, class: 'form-control' %>

      <%= f.submit "更新する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, '一覧') %>

<% if params[:search].blank? %>
    <h1>全てのユーザー</h1>
<%else%>
    <h1>検索結果</h1>
<%end%>

<!--  検索拡張機能  -->
 <div id="form1">
      <p>ユーザー名検索</p>
      <%= form_tag(users_path, :method => 'get' ) do %>
      <%= text_field_tag :search, value="", id: "sbox"%>
      <%= submit_tag '検索', :name => nil, id: "sbtn" %>
      <% end %>
 </div>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, '新規作成') %>
<% provide(:button_text, '作成する') %>
<h1>ユーザー作成</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, '勤怠表示') %>
<div>
  <table class = "table-bordered table-condensed">
    <tr>
      <td>
        <%= link_to "←", user_path(params: {id: @user.id, first_day: @first_day.prev_month }),
                         class: "btn btn-xs btn-primary" %>
        &emsp;<%= @first_day.to_s(:year_month) %>　時間管理表&emsp;
        <%= link_to "→", user_path(params: {id: @user.id, first_day: @first_day.next_month }),
                         class: "btn btn-xs btn-primary" %>
      </td>
      <td>指定勤務時間　<%= format_basic_time(@user.work_time) %></td>
      <td>基本時間　<%= format_basic_time(@user.basic_time) %></td>
      <td>初日　<%= @first_day.to_s(:date) %></td>
    </tr>
    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未設定" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>出勤日数：<%= @worked_sum %>日</td>
      <td>締日　<%= @last_day.to_s(:date) %></td>
    </tr>
  </table>
  <%= link_to "残業申請のお知らせ", "#" if current_user.superior1 || current_user.superior2%>

  <%= link_to "勤怠を編集", edit_attendances_path(@user, @first_day), class: "btn btn-primary" %>
  <%= link_to "CSV出力", user_path(format: :csv), class: "btn btn-primary" %>
  <%= link_to "勤怠修正ログ(修正済み)", "#", class: "btn btn-primary" %>

  <table class = "table-bordered table-striped table-condensed">
    <thead>
      <tr> <!--rowspan:縦結合、colspan：横結合-->
        <th rowspan = "3">残業申請</th>
        <th rowspan = "3">日付</th>
        <th rowspan = "3">曜日</th>
        <th colspan="8">【実績】</th>
        <th colspan="5">所定外勤務</th>
      </tr>
      <tr>
        <th colspan = "3">出社</th>
        <th colspan = "3">退社</th>
        <th rowspan = "2">在社時間</th>
        <th rowspan = "2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">支持者確認</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>
    <tbody>
      <% @dates.each do |day| %>
        <tr>
          <td>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Modal" 
                data-date="<%= day.worked_on.to_s(:date) %>" 
                data-youbi="<%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %>"
                >
                残業申請
            </button>
          </td>
          <td><%= day.worked_on.to_s(:date) %></td>
          <td class="<% if day.worked_on.wday==0 %>
                           sunday
                        <% elsif day.worked_on.wday==6%>
                           saturday
                         <%end%>"><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
          <td><%= started_at_hour = day.started_at.to_s(:hour) if day.started_at.present? %></td>
          <td>
            <% if day.started_at.present? %>
            <% started_at_minute=day.started_at.to_s(:min) %>
            <%= (started_at_minute.to_i)/15.truncate(0)*15 %>
            <%end%>
          </td>
          <td>
            <% if day.worked_on == Date.today && day.started_at.nil? %>
              <%= button_to "出社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
            <% end %>
          </td>
          <td><%= day.finished_at.to_s(:hour) if day.finished_at.present? %></td>
          <td>
            <% if day.finished_at.present? %>
            <% finished_at_minute=day.finished_at.to_s(:min) %>
            <%= (finished_at_minute.to_i)/15.truncate(0)*15 %>
            <%end%>
          </td>
          <td>
            <% if day.worked_on == Date.today && day.started_at.present? && day.finished_at.nil? %>
              <%= button_to "退社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
            <% end %>
          </td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= working_times_indicate_15minutes(day.started_at, day.finished_at) %>
              <% seconds = (day.finished_at - day.started_at).to_i %>
              <% @total_seconds = @total_seconds.to_i + seconds %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan = "2"><%= format_basic_time(@user.basic_time).to_f * @worked_sum %></td>
        <td colspan = "6"></td>
        <td><%= working_times_sum(@total_seconds) unless @total_seconds.nil? %></td>
        <td></td>
      </tr>
    </tfoot>
  </table>
</div>

          <%= render 'overwork-modal' %>